[package]
name = "lc3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.4.16", features = ["derive"] }
ctrlc = "3.4.2"
libc = "0.2.151"
termios = "0.3.3"
